# Generated by Django 5.1.3 on 2025-05-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomi')),
                ('lat', models.FloatField(blank=True, default=0, null=True, verbose_name='Kenglik')),
                ('long', models.FloatField(blank=True, default=0, null=True, verbose_name='Uzunlik')),
            ],
            options={
                'verbose_name': 'LocationModel',
                'verbose_name_plural': 'LocationModels',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon raqam')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol'), ('other', 'Pochta')], default='male', max_length=100, verbose_name='Jins')),
                ('count', models.CharField(choices=[('one', '1 kishi'), ('two', '2 kishi'), ('there', '3 kishi'), ('four', '4 kishi')], default='one', max_length=100, verbose_name='Odam soni')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.locationmodel', verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'OrderModel',
                'verbose_name_plural': 'OrderModels',
                'db_table': 'order',
            },
        ),
    ]
