# Generated by Django 5.1.3 on 2025-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Telefon raqam'),
        ),
    ]
