# Generated by Django 5.1.3 on 2025-05-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ordermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Telefon raqam'),
        ),
    ]
